### ISSUE TITLE
test_cpp compile issue

### ISSUE THREAD

**Issue by yaseryacoob** [aboulch/normals_Hough#7]
when compiling on ubuntu 16.04, the test_cpp fails  with 

........../normals_Hough/test_cpp/../third_party_includes/nanoflann.hpp:1823:16: error: âlog2â is not a member of âstdâ
    treeCount = std::log2(maximumPointCount);
-------------------------------------------------------------------------
the nanoflann.hpp treeCount = std::log2(maximumPointCount); is incompatible with something?

**Comment by aboulch** [comment]
I fixed compilation problems. Updated Eigen and Nanoflann.
Seems to work fine on fresh ubuntu 18.04 install + Anaconda

**Comment by yaseryacoob** [comment]
Thanks for the effort, unfortunately I am running on 16.04 and it does not build, I get errors such as

/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

I tried to add reference to  gcc/8.1.0 but that didn’t help.
Which gcc is running on 18.04?
